---
author: "NASA GeneLab Project"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# `r opt$glds` Raw Data QA Summary
#### `r Sys.Date()`
#### Organism: `r opt$species`
#### Platform: `r opt$platform` Microarray `r class(raw)`
```{r echo=FALSE}
show(raw)
```

## Study Sample Factor Grouping
```{r echo=FALSE}
  DT::datatable(targets$t1)
```

## Raw Data MA Plots
```{r eval=(plots == "OLIGO"), echo=FALSE}
count <- dim(targets$t1)[1]
printrows <- ceiling(count/2)
#par(mfrow = c(printrows,2),mar=c(1,1,1,1))
for (i in 1:count){
  oligo::MAplot(raw,which=i, pairs=FALSE)
  }

```
```{r eval=(plots == "LIMMA"), echo=FALSE}
count <- dim(targets$t1)[1]
printrows <- ceiling(count/2)
#par(mfrow = c(printrows,2),mar=c(1,1,1,1)) 
for (i in 1:count){
  limma::plotMD(raw, column = i, xlab = "Average log-expression", ylab = "log-fold-change", main = colnames(raw)[i])
  }

```

## Raw Data Density Plot
```{r eval=(plots == "OLIGO"), echo=FALSE}

if (class(raw)=="ExonFeatureSet" || class(raw)=="GeneFeatureSet"){
  oligo::hist(raw, main = paste0(opt$glds," Raw Intensity Distributions"), target="probeset",xlab="Intentisty",ylab="Density",col=rainbow(count),lty=1)
  legend("topright",legend=targets$t1$SampleName,fill = rainbow(count))
}else{
  oligo::hist(raw, main = paste0(opt$glds," Raw Intensity Distributions"),xlab="Intentisty",ylab="Density",col=rainbow(count),lty=1)
  legend("topright",legend=targets$t1$SampleName,fill = rainbow(count))
}

```
```{r eval=(plots == "LIMMA"), echo=FALSE}

plotDensities(raw, legend = FALSE)
legend("topright",legend=targets$t1$SampleName,fill = rainbow(count))

```

## Raw Data Box Plot
```{r eval=(plots == "OLIGO"), echo=FALSE}
if (class(raw)=="ExonFeatureSet" || class(raw)=="GeneFeatureSet"){
oligo::boxplot(raw,which="pm",transfo=log2, nsample=10000,main=paste0(opt$glds," Raw Data Log2 Intensities"), las=2,outline=FALSE,ylab = "log2 Intensities", target="probeset")
}else{
oligo::boxplot(raw,which="pm",transfo=log2, nsample=10000,main=paste0(opt$glds," Raw Data Log2 Intensities"), las=2,outline=FALSE,ylab = "log2 Intensities")
}
```
```{r eval=(plots == "LIMMA"), echo=FALSE}
boxplot(data.frame(log2(as.matrix(raw))),main="Raw Data Log2 Intensities", las=2,outline=FALSE)
```

## Raw Data PCA Plot
```{r echo=FALSE, message=FALSE, warning=FALSE, eval=(targets$labels == 1)}
library(ggplot2)
try(exp_raw <- log2(exprs(raw)))
try(exp_raw <- log2(as.matrix(raw)))
PCA_raw <- prcomp(t(exp_raw), scale. = FALSE)
try({PCA_raw <- prcomp(t(exp_raw), scale. = TRUE)}) # scaling will fail for low replicates
percentVar <- round(100*PCA_raw$sdev^2/sum(PCA_raw$sdev^2),1)
sd_ratio <- sqrt(percentVar[2] / percentVar[1])
dataGG <- data.frame(PC1 = PCA_raw$x[,1], PC2 = PCA_raw$x[,2], Group = targets$t1$Group)
PCA_plot <- ggplot(dataGG, aes(PC1, PC2)) +
      geom_point(aes(colour = Group)) +
  ggtitle("Raw Data PCA Plot of log2 Expression") +
  xlab(paste0("PC1, VarExp: ", percentVar[1], "%")) +
  ylab(paste0("PC2, VarExp: ", percentVar[2], "%"))
plot(PCA_plot)

path <- file.path(workdir,"Processed_Data",opt$glds,"00-RawData")
setwd(path)
write.csv(PCA_raw$x, file = "visualization_PCA_table.csv")
rm(exp_raw, PCA_raw,dataGG, PCA_plot,percentVar,sd_ratio,path)
```

## Array Spot Log Intensity Images
```{r eval=(plots == "OLIGO"),echo=FALSE}

#par(mfrow = c(printrows,2),mar=c(1,1,1,1))
for (i in 1:count){
  oligo::image(raw, transfo=log2, which=i)
  }
```
```{r eval=(plots == "LIMMA"),echo=FALSE}
#par(mfrow = c(printrows,2),mar=c(1,1,1,1))
for (ind in 1:count){
  if (opt$platform == "Agilent"){
  r <- raw$genes$Row
  c <- raw$genes$Col
  nr <- max(r)
  nc <- max(c)
  i <- (r-1)*nc+c
  y <- rep(NA,length(i))
  y[i] <- log2(raw$Eb[,ind])
  raw$printer <- list(ngrid.r=1,ngrid.c=1,nspot.r=nr,nspot.c=nc) 
}
  imageplot(y,raw$printer, main=colnames(raw$Eb)[ind])
  }
```
